// import './imgToTxt.test'
// import './firework.test'
// import './firework2.test'
// import './imgToFade.test'
// import './NoteBoard.test'
import './captureVideoFrame.test'
// import './shotImg.test'
// import './handleImg.test'
// import './imgToNoise.test'